### ISSUE TITLE
out-of-tree builds

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pd.cmake#12]
being able to build the same source into different flavours (defined by the build-system) is decidedly cool.

for this to work in all cases, the *only* directory we ever want to put stuff into is the *build* directory, never the *source* directory.
that is, the following should not return anything:
```
cmake -B _build
make -C _build
rm -rf _build
git status --porcelain --ignored
```

this means, that we must never put anything into `CMAKE_(CURRENT_)SOURCE_DIR`, only ever use  `CMAKE_(CURRENT_)BINARY_DIR` to write files to.

i think c1acbcde3770129a481b2e6369da92086ba4a52c tried to fix this, but got it wrong.

personally i would prefer if the *default* output path would just be the build directory, and not some subdir where i have to first search for the externals:

```cmake
set(PD_OUTPUT_PATH ${CMAKE_CURRENT_BUILD_DIR} CACHE PATH "Path to the output of the external")
```

**Comment by charlesneimog** [comment]
This is already fixed here: https://github.com/charlesneimog/pd.cmake/commit/8c710285ae8aa282f82c758386435aeeb1dc4d4c.

Obs.: I will do my messy commits there, then I make it clear here.

**Comment by charlesneimog** [comment]
#14
