### ISSUE TITLE
move build-system for examples into `Examples/`

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pd.cmake#13]
we currently have a master `CMakeLists.txt` file in the project root, the sole purpose of which is to act as an example on how to use `pd.cmake`.

since it is just an example, i think it should be moved into the `Examples/` subdirectory.

we could leave a Cmakefile in the root, that just calls the Examples.

this way, the examples are "self-contained" (without `pd.cmake` itself) and can also document how to include `pd.cmake` from arbitrary paths (see my `PDCMAKE_DIR` in #7 )

**Comment by charlesneimog** [comment]
#10

**Comment by umlaeute** [comment]
it's not related to #10, and i don't see that it is resolved in current `master` or `dev` branch.

**Comment by charlesneimog** [comment]
Check 1f0f4f470cabf824b08265f28d70a892b2c704ca, I don't think that we need two `CMakeLists.txt`, one in the root with a simple `add_subdirectory` for Examples.

**Comment by umlaeute** [comment]
I think otherwise, but I already said everything (explaining why I think so) in the top level post, so I don't know what to add...

**Comment by charlesneimog** [comment]
ok, I am not sure if I understand, but I implemented what I understood here: 20afecff670c158c8577d201bbf7f2d744c75044

**Comment by umlaeute** [comment]
Am 18. Juni 2024 16:28:22 MESZ schrieb "Charles K. Neimog" ***@***.***>:
>ok, I am not sure if I understand, but I implemented what I understood here: 20afecff670c158c8577d201bbf7f2d744c75044
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pure-data/pd.cmake/issues/13#issuecomment-2176245221
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
Cool. 

I wonder: do we need the `${CMAKE_CURRENT_SOURCE_DIR}/`, or could we just specify relative paths? 


mfg.gss.owh
IOhannes

**Comment by charlesneimog** [comment]
Done in cff4701!
