### ISSUE TITLE
README confused about 'PD_CMAKE_PATH' vs 'PDCMAKE_DIR'

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pd.cmake#17]
reading the README, it is unclear whether one should use `PD_CMAKE_PATH` or `PDCMAKE_DIR` to set the location of `pd.cmake`.

we should strive for consistency with pd-lib-builder, but we *must* have internal consistency :-)
ideally we reach internal consistency while staying consistent with pd-lib-builder.

(also the confusion can be found in `pd.cmake`, `Examples/CMakeLists.txt` and `Tests/01.Deprecated-Functions/CMakeLists.txt`)

**Comment by charlesneimog** [comment]
Thanks!
